#!/usr/bin/env python3
"""Refresh posts.js from the Project Spica Substack feed.

Run this whenever you want the website's "Recent writing" list to pick up new
posts:

    python3 fetch_posts.py

It reads the publication's public RSS feed, takes the newest few posts, and
writes them to posts.js as `window.POSTS = [...]` — the same global-on-a-file
pattern as stars.js. The page reads that file on load and renders the cards, so
there is no build step or server involved: refreshing the site is just rerunning
this script and committing the updated posts.js.

Uses only the Python standard library, so there is nothing to install.
"""
import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from email.utils import parsedate_to_datetime

# Defaults to our own feed; pass a different feed URL as the first argument to
# preview the page against someone else's publication.
FEED_URL = sys.argv[1] if len(sys.argv) > 1 else 'https://projectspica.substack.com/feed'
MAX_POSTS = 4          # how many recent posts to show on the page
EXCERPT_CHARS = 180    # trim each summary to roughly this many characters

# The one RSS namespace we need: Substack puts the full post body under
# <content:encoded>, which we mine for a cover image when there's no enclosure.
NS = {'content': 'http://purl.org/rss/1.0/modules/content/'}

def strip_html(html):
    text = re.sub(r'<[^>]+>', '', html)        # drop every tag
    text = re.sub(r'\s+', ' ', text).strip()    # collapse runs of whitespace
    return text

def first_image(item):
    # Substack usually exposes the cover image as an <enclosure>; if it's
    # missing, fall back to the first <img> found in the post body.
    enclosure = item.find('enclosure')
    if enclosure is not None and enclosure.get('url'):
        return enclosure.get('url')
    body = item.findtext('content:encoded', default='', namespaces=NS)
    match = re.search(r'<img[^>]+src="([^"]+)"', body)
    return match.group(1) if match else None

def main():
    # A User-Agent header avoids the occasional bot block on the feed.
    request = urllib.request.Request(FEED_URL, headers={'User-Agent': 'project-spica-fetch'})
    with urllib.request.urlopen(request) as response:
        tree = ET.parse(response)

    posts = []
    for item in tree.findall('.//item')[:MAX_POSTS]:
        summary = strip_html(item.findtext('description', default=''))
        # Trim to a whole word so the excerpt never ends mid-word.
        if len(summary) > EXCERPT_CHARS:
            summary = summary[:EXCERPT_CHARS].rsplit(' ', 1)[0] + '…'

        # NOTE: [edge case callout] A well-formed Substack item always carries a
        # pubDate; if a feed ever omits it, parsedate_to_datetime(None) would
        # raise. Left unguarded to keep the happy path clear.
        published = parsedate_to_datetime(item.findtext('pubDate'))

        posts.append({
            'title': item.findtext('title', default='').strip(),
            'url': item.findtext('link', default='').strip(),
            'date': published.strftime('%B %-d, %Y'),   # e.g. "June 24, 2026"
            'excerpt': summary,
            'image': first_image(item),
        })

    with open('posts.js', 'w') as file:
        file.write('// Generated by fetch_posts.py from the Project Spica Substack feed.\n')
        file.write('// Run `python3 fetch_posts.py` to refresh.\n')
        file.write('window.POSTS = ' + json.dumps(posts, indent=2, ensure_ascii=False) + ';\n')
    print(f'Wrote {len(posts)} post(s) to posts.js')

if __name__ == '__main__':
    main()
