// Generated by fetch_posts.py from the Project Spica Substack feed.
// Run `python3 fetch_posts.py` to refresh.
window.POSTS = [
  {
    "title": "Correcting test set contamination with spiking",
    "url": "https://projectspica.substack.com/p/correcting-test-set-contamination",
    "date": "July 25, 2026",
    "excerpt": "By intentionally contaminating some test examples at known rates, we can train a probe to detect contaminated examples and drop them from the test set.",
    "image": "https://substackcdn.com/image/fetch/$s_!xlJF!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe83b220d-aeee-465d-bd65-c5b6e916fff7_1196x416.png"
  },
  {
    "title": "Project Spica announced at the NIST-University Summit",
    "url": "https://projectspica.substack.com/p/project-spica-announced-at-the-nist",
    "date": "July 2, 2026",
    "excerpt": "Our mission: establish spiking as a measurement standard for AI.",
    "image": "https://substackcdn.com/image/fetch/$s_!ntW0!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5fcea9c0-7adc-4efe-abc3-26de9bf44764.heic"
  }
];
