// Generated by fetch_posts.py from the Project Spica Substack feed.
// Run `python3 fetch_posts.py` to refresh.
window.POSTS = [
  {
    "title": "What it feels like to work with Mythos",
    "url": "https://www.oneusefulthing.org/p/what-it-feels-like-to-work-with-mythos",
    "date": "June 9, 2026",
    "excerpt": "Claude Fable represents another big jump in AI",
    "image": "https://substackcdn.com/image/fetch/$s_!hxhY!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ff58114c7-7286-4a9f-ab75-3c8a7e414dc3_2382x1247.png"
  },
  {
    "title": "Co-Existence and the End of Co-Intelligence",
    "url": "https://www.oneusefulthing.org/p/co-existence-and-the-end-of-co-intelligence",
    "date": "June 4, 2026",
    "excerpt": "Also: how pitch a book to an AI!",
    "image": "https://substackcdn.com/image/fetch/$s_!j3el!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe4118cc4-8494-491f-8bb7-c78882e26467_1731x909.png"
  },
  {
    "title": "Choosing to Stay Human",
    "url": "https://www.oneusefulthing.org/p/choosing-to-stay-human",
    "date": "May 26, 2026",
    "excerpt": "If you go to your favorite social media site, you will find it full of posts that start to look suspiciously similar to each other:",
    "image": "https://substackcdn.com/image/fetch/$s_!a8R9!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb63d669d-64f1-4f8b-81ae-9476d20a720d_1182x635.png"
  },
  {
    "title": "Sign of the future: GPT-5.5",
    "url": "https://www.oneusefulthing.org/p/sign-of-the-future-gpt-55",
    "date": "April 23, 2026",
    "excerpt": "One impressive step on the curve",
    "image": "https://substackcdn.com/image/fetch/$s_!hesI!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F2c591570-ee4a-4107-a9d1-b167d3f4a64a_1484x1060.png"
  }
];
